=== standpoint/recently/TASK#3_XML/depo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="bank" type="TypeBank" />
  <xs:complexType name="TypeBank">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
      <xs:element name="country" type="TypeContry" />
      <xs:element name="type" type="TypeDepositeType" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="TypeContry">
    <xs:restriction base="xs:NCName">
      <xs:enumeration value="Ukraine" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="TypeDepositeType">
    <xs:sequence>
      <xs:element name="demand" type="TypeDeposite" />
      <xs:element name="fixed" type="TypeDeposite" />
      <xs:element name="payment" type="TypeDeposite" />
      <xs:element name="savings" type="TypeDeposite" />
      <xs:element name="metal" type="TypeDeposite" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TypeDeposite">
    <xs:sequence>
      <xs:element name="depositor" type="TypeDepositor" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TypeDepositor">
    <xs:sequence>
      <xs:element name="fullname" type="TypeFullname" />
      <xs:element name="account" type="TypeAccount" />
      <xs:element name="amount" type="TypeAmount" />
      <xs:element name="profitability" type="TypeProfit" />
      <xs:element name="period" type="TypePeriod" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required" />
  </xs:complexType>
  <xs:simpleType name="TypeFullname">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][a-z]*\s[A-Z][.][A-Z][.]"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TypeAccount">
    <xs:restriction base="xs:long">
      <xs:minExclusive value="20000000000000"></xs:minExclusive>
      <xs:maxExclusive value="30000000000000"></xs:maxExclusive>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TypeAmount">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2" />
      <xs:minInclusive value="100.00" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TypeProfit">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2" />
      <xs:minInclusive value="0.50"></xs:minInclusive>
      <xs:maxExclusive value="33.00"></xs:maxExclusive>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TypePeriod">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="31" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== standpoint/recently/TASK#3_XML/depo.xml
<?xml version="1.0" encoding="UTF-8"?>
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="depo.xsd">
    <name>OTP Bank</name>
    <country>Ukraine</country>
    <type>
        <demand>
            <depositor id="ID-00001">
                <fullname>Dubina M.O.</fullname>
                <account>26258455049783</account>
                <amount>10000.00</amount>
                <profitability>11.0</profitability>
                <period>730</period>
            </depositor>
            <depositor id="ID-000002">
                <fullname>Goncharenko A.L.</fullname>
                <account>26258455049745</account>
                <amount>15000.00</amount>
                <profitability>11.5</profitability>
                <period>1095</period>
            </depositor>
        </demand>
        <fixed>
            <depositor id="ID-000003">
                <fullname>Kushnarev M.V.</fullname>
                <account>26258455045501</account>
                <amount>75000.00</amount>
                <profitability>23.0</profitability>
                <period>366</period>
            </depositor>
        </fixed>
        <payment>
            <depositor id="ID-000004">
                <fullname>Goncharenko A.L.</fullname>
                <account>26258455049745</account>
                <amount>10000.00</amount>
                <profitability>13.5</profitability>
                <period>183</period>
            </depositor>
        </payment>
        <savings>
            <depositor id="ID-000005">
                <fullname>Gorobec V.F.</fullname>
                <account>26258455048452</account>
                <amount>2500.00</amount>
                <profitability>21.5</profitability>
                <period>730</period>
            </depositor>
        </savings>
        <metal>
            <depositor id="ID-000006">
                <fullname>Bezruk V.K.</fullname>
                <account>26258455042387</account>
                <amount>700.00</amount>
                <profitability>4.3</profitability>
                <period>730</period>
            </depositor>
        </metal>
    </type>
</bank>
